blueprint:
  name: sleif dehumidifier full notification
  description: Send a notification when the water tank is full
  domain: automation

  input:
    humidity_current:
      name: Humidity sensor
      description: "Sensor that contains the current humidity"
      selector:
        entity:
          domain: sensor
          device_class: humidity
          multiple: false
    humidity_warning:
      name: Humidity warning threshold
      description: "Humidity warning threshold"
      default: none
      selector:
        number:
          min: 50
          max: 80
          step: 5
          unit_of_measurement: "%"
    power_plug_1_switch:
      name: Dehumidifier switch
      description: "Switch entity of the power plug of the dehumidifier"
      selector:
        entity:
          domain: switch
          multiple: false
    power_plug_1_power:
      name: Dehumidifier power entity
      description: "Power entity of the power plug of the dehumidifier"
      selector:
        entity:
          domain: sensor
          device_class: power
          multiple: false
    actions_notificactions:
      name: Action(s) when the threshold value has been exceeded
      default: []
      selector:
        action: {}

trigger:
- platform: state
  entity_id:
    - !input power_plug_1_switch
- platform: numeric_state
  entity_id:
    - !input humidity_current
  above: !input humidity_warning
  for:
    hours: 0
    minutes: 15
    seconds: 5
- platform: event
  event_type:
    - automation_reloaded

condition:
  - condition: numeric_state
    entity_id: !input power_plug_1_power
    below: 2
  - condition: state
    entity_id: !input power_plug_1_switch
    state: "on"

action:
- choose: []
  default: !input actions_notificactions
