blueprint:
  name: sleif dehumidifier - status notifications
  description: "`- Version: 1.4 -`\n\nNotifies about important device status changes."
  domain: automation

  input:
    dehumidifier_status_code:
      name: Status Code Sensor
      description: "Sensor that contains the current humidity"
      selector:
        entity:
          domain: sensor
          # device_class: humidity
          multiple: false
    notify_service:
      name: Notification Service
      selector:
        entity:
          domain: notify
trigger_variables:
  _dehumidifier_status_code: !input dehumidifier_status_code

trigger:
  - platform: state
    entity_id:
      - !input dehumidifier_status_code
    for:
      hours: 0
      minutes: 5
      seconds: 0
    to:
      - unavailable
      - unknown
      - "1"
  - platform: template
    value_template: "{{ states(_dehumidifier_status_code) | int % 2 == 1 }}"
    for:
      hours: 0
      minutes: 5
      seconds: 0

actions:
  - action: !input notify_service
    metadata: {}
    data:
      message: >
        "{{ 'Entfeuchter Tank leeren: ' ~ this.attributes.friendly_name if trigger.to_state.state == '1'
        else this.attributes.friendly_name ~ ': ' ~ trigger.to_state.state }}"
